Multi instance checker
ddps-lab/spot-checker pull request #38
Opened 2024-08-20 02:41 UTC by mumat0103

Multi node SpotChecker 가 main 브랜치에 merge 되지 않아서 합치는 작업 진행하겠습니다.

2024-08-23 01:26 UTC, red0sena commented
예전에 스팟인스턴스 init시간을 측정하기 위해 shutdown 명령어을 usercode에코드에 넣었는데 multinode spotchecker에서는 필요 없음으로 이부분을삭제 하였습니다.

2024-08-23 03:42 UTC, mh3ong requested changes

2024-08-23 03:42 UTC, mh3ong commented on aws/data/workloads_10.txt
이러한 workload 정보는 gitignore에 추가되어야할 것 같습니다.

2024-08-23 03:42 UTC, mh3ong commented on aws/spot-health-checker.py
> +            'Arn': '' # IAM ARN for S3 access
IAM Arn은 변수처리가 필요해 보입니다.
S3 Permission이 필요하다면 이에 필요한 IAM Role을 생성/삭제 하는것이 추후 실행 시 복잡도를 줄일 것 같습니다.

2024-08-23 03:42 UTC, mh3ong commented on multinode_ondemand_checker/export_log.py
현재 이 코드와 같이 boto3를 사용해 log를 export하는 것은 100개가 넘어가는 로그는 정상적으로 export가 되지 않을 것으로 보여 multinode_spot_checker에서 수정했던 방식으로 log를 추출하도록 코드 수정이 필요합니다.

2024-08-23 03:42 UTC, mh3ong commented on multinode_ondemand_checker/ondemand-instance-checker.py
> +sudo shutdown -P +%s
spotchecker와 달리 ondemand노드는 shutdown한다는 것을 명식적으로 주석을 통해 표시할 필요가 있어보입니다.

2024-08-23 03:58 UTC, mumat0103 commented on multinode_spot_checker/aws/export_result.py
> +    with open('regions.txt', 'r', encoding='utf-8') as file:
regions.txt 파일의 샘플이 있어야 합니다.

2024-08-24 05:18 UTC, red0sena commented
spot-checker에 해당하는 코멘트 수정하였습니다.

2024-08-26 20:35 UTC, red0sena commented
https://github.com/ddps-lab/research-issues/issues/569#issuecomment-2311021894 코멘트에서 InsufficientInstanceCapacity가 발생하여 spot-request가 failed가 되어버리는 이슈가 있었습니다. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-capacity
위 링크에서는 해결방법으로 한번에 많은 스팟 노드 개수를 request하지 말고 따로 따로 request를 하라고 되어 있어 해당 방식으로 코드를 수정하였습니다.

2024-08-26 22:35 UTC, kmu-leeky commented
그런데 이렇게 되면, spot request limit 에 걸릴 수 있지 않을까? 그리고 하나의 PR 에 너무 많은 코드가 들어가서 코드를 리뷰하기가 어렵네. 리뷰된 부분은 머지를 하고 새로운 PR 로 코드를 보는게 좋겠다.

2024-08-27 03:41 UTC, red0sena approved these changes
확인하였습니다.

2025-08-12 06:07 UTC, closed without merging