GCP checker 생성
ddps-lab/spot-checker pull request #6
Opened 2022-10-13 08:14 UTC by cg10036

#5 
현재까지 작성된 GCP 체커 모듈입니다.

2022-10-13 13:53 UTC, kmu-leeky reviewed
잘했네요. 코드도 보기 좋고 잘동작할듯 하네요. @james-sungjae-lee  가 한번 더 리뷰해보고 머지 하면 될듯해요.

2022-10-13 13:53 UTC, kmu-leeky commented on gcp/spot-health-checker.py
> +                    start_instance(PROJECT_NAME, instance_zone, instance_name)
GCP 는 동작하다가 terminate 가 된건 다시 start 를 한다는 거죠? 새로운 spot request 를 만드는건 아니고?

2022-10-13 13:53 UTC, kmu-leeky commented on gcp/spot-health-checker.py
> +    with open(f"./logs/{instance_type}_{instance_zone}_{launch_time}.json", "w") as f:
로그 저장은 모든 실험을 마치고 한번에 하게 되는거죠? 이렇게 되면 중간에 이슈가 생겨서 실험이 한번에 깔끔하게 끝나지 않으면 모두 로그가 유실되는 위험이 있는듯해요. 적어도 한시간에 한번 정도는 로그 파일로 기록을 하면서 진행을 하는건 어떨까요?

2022-10-13 13:58 UTC, cg10036 commented on gcp/spot-health-checker.py
> +                    start_instance(PROJECT_NAME, instance_zone, instance_name)
네 맞습니다. 작동이 중지된 기존의 인스턴스를 다시 시작합니다.

2022-10-13 14:38 UTC, cg10036 commented on gcp/spot-health-checker.py
> +    with open(f"./logs/{instance_type}_{instance_zone}_{launch_time}.json", "w") as f:
네 교수님. 해당 기능 추가했습니다.

2022-10-14 00:24 UTC, kmu-leeky approved these changes
로그 메시지의 경우 [] 에 계속 보관하고 있다가, 1시간에 한번씩 이전 로그는 .bak 으로 백업 보관하고, 동시에 그 당시의 리스트에 있는 모든 메시지를 write 하는듯 하네요. 로그 메시지가 많이 커지지는 않을듯 해서 괜찮을것 같기는 해요. 그런데 우리가 실제로 실험을 하면 인스턴스 종류를 한번에 300~500 개 실험을 진행할 수 있어요. 그럴 경우에도 이런방식으로 write 하는데 따른 오버헤드를 버텨낼수 있을런지 한번 계산해봅시다. 잘 구현했네요.

2022-10-14 00:36 UTC, cg10036 commented
넵 교수님. 24시간 가동했을때 로그파일은 약 1.4MB이고 500개를 동시에 가동할시 로그가 저장될때마다 약 700MB를 write해야해서 문제가 생길 수 있음을 인지했습니다. csv와 같은 포맷을 이용해 기존의 파일에 append하는 방식으로 오버헤드를 줄여보겠습니다.

2022-10-14 00:45 UTC, kmu-leeky commented
약간 경계선이네요. 시간당 700 메가라, 그건 파일 사이즈가 커지는 후반부 일테고, 한시간에 한번씩 시차를 두고 발생할테니 왠만한 서버에서는 괜찮을것 같기도 하고.. 그냥 시험 삼아서 조금 큰 서버 하나 켜서 24시간 동안 수집한 로그 메시지 읽어서 파일로 저장하는 프로세스를 한 500개 구동 시켜서 동시에 write 하게 했을때 무리없이 동작하는지 테스트 해봐도 괜찮을것 같아요. 아예 처리하기 힘들 정도의 write 양은 아닌듯 해요.

2022-10-14 00:59 UTC, james-sungjae-lee requested changes
Checker 에서 sleep 모듈을 사용하여 5초 간격이 되도록 설정되어 있네요. 이렇게 작업하면 write 오버헤드가 증가할 수록 오차가 점차 커지는 것을 확인했습니다. AWS 때에는 늦게 발견하여 이 점까지는 반영하지 못했지만, GCP Checker 는 새롭게 개발하는 모듈이니 이 점을 반영하면 좋겠습니다.

일부 한글로 된 주석은 영어로 수정 부탁드립니다

PROJECT NAME 은 주석 처리 되어있는데 굳이 필요하지 않다면 지워도 괜찮을까요?

2022-10-14 01:38 UTC, cg10036 commented
PROJECT_NAME, 기타 한글로 된 주석 제거했습니다.
sleep 모듈로 인한 오차 수정했습니다.
json에서 csv로 포맷을 변경해 오버헤드를 줄였습니다.

2022-10-14 01:38 UTC, cg10036 commented
<img width="258" alt="스크린샷 2022-10-14 오전 10 38 38" src="https://user-images.githubusercontent.com/30382481/195742297-eca62836-a742-44d2-8d98-8cceb7fc3219.png">
로그는 다음과 같이 저장되게 됩니다.

2022-10-14 02:50 UTC, james-sungjae-lee approved these changes
간단히 보았을 때에는 단순히 sleep 을 사용하지 않고 기록 시점을 기준으로 다음 로깅 시점을 지정하여 작동하는 것 같네요. 검증까지 해서 기존보다는 훨씬 나은 코드가 되었습니다. 코드 리팩토링을 잘 해주어서 이대로 merge 해도 괜찮을 것 같습니다.

하지만 제가 의도한 바는 아예 sleep 을 사용하지 않고 logging 하는 것을 말한 것이었어요. sleep 없이 정확하게 특정 시간에 python logging 이 작동하도록 하는 것도 생각해보면 좋겠습니다. sleep 은 지연을 준다는 것이지, 정확하게 특정 시점에 작동하게 하는 것이 아니니까요.

2022-10-14 02:51 UTC, james-sungjae-lee commented
한 가지만 더 부탁하고 싶은 사항이 있는데, 현재 코드에서 Readme 를 제외한 파일들을 aws 디렉토리를 생성하여 넣어줄 수 있나요? 그렇게 하면 #2 이슈도 한 번에 처리 가능할 것 같네요

2022-10-14 03:46 UTC, kmu-leeky commented
https://github.com/ddps-lab/spot-checker/pull/6#issuecomment-1278402337 @james-sungjae-lee  디렉토리 구성 변경은 별도의 PR 로 진행하는게 낫겠다. 그것과 #2 를 연결해서 함께 resolve 되도록.

2022-10-14 03:47 UTC, james-sungjae-lee commented
네 그러면 이 이슈는 merge 하고 별도의 PR 로 진행하겠습니다

2022-10-14 03:47 UTC, merged